mb_github_auth:
    resource: "@MBGithubAuthBundle/Resources/config/routing.xml"
    prefix:   /

mb_extending_symfony:
    resource: "@MBExtendingSymfonyBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"