mb_extending_symfony_event:
    resource: "@MBExtendingSymfonyBundle/Resources/config/routing/event.yml"
    prefix:   /event

mb_extending_symfony_homepage:
    path:     /hello/{name}
    defaults: { _controller: MBExtendingSymfonyBundle:Default:index }
