mb_extending_symfony_event:
    resource: "@MBExtendingSymfonyBundle/Resources/config/routing/event.yml"
    prefix:   /event

mb_extending_symfony_homepage:
    path:     /hello/{name}
    defaults: { _controller: MBExtendingSymfonyBundle:Default:index }

mb_geo_index:
    path:     /
    defaults: { _controller: MBExtendingSymfonyBundle:Geo:index }

mb_geo_event_join:
    path: /event/{eventId}/join
    defaults: { _controller: MBExtendingSymfonyBundle:Geo:join }

mb_coordinate_form:
    path: /map
    defaults: { _controller: MBExtendingSymfonyBundle:Form:map }

mb_address_form:
    path: /address
    defaults: { _controller: MBExtendingSymfonyBundle:Address:address }