services:
#    mb_extending_symfony.example:
#        class: MB\Bundle\ExtendingSymfonyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    geocoder_adapter:
        class: Geocoder\HttpAdapter\CurlHttpAdapter
        public: false

    geocoder_provider:
        class: Geocoder\Provider\FreeGeoIpProvider
        public: false
        arguments: [ @geocoder_adapter ]

    geocoder:
        class: Geocoder\Geocoder
        calls:
            - [ registerProviders, [[ @geocoder_provider ]] ]

    freegeoip_geocoder:
        class: MB\Bundle\ExtendingSymfonyBundle\Geo\FreeGeoIpGeocoder
        arguments: [ @geocoder ]
        tags:
            - { name: mb.geocoder }

    random_geocoder:
        class: MB\Bundle\ExtendingSymfonyBundle\Geo\RandomLocationGeocoder
        tags:
            - { name: mb.geocoder }

    mb.user_locator:
        class: MB\Bundle\ExtendingSymfonyBundle\Geo\UserLocator
        scope: request
        arguments: [ @geocoder, @request ]

    join_meetup_listener:
        class: MB\Bundle\ExtendingSymfonyBundle\Event\JoinMeetupListener
        tags:
            - { name: kernel.event_listener, event: meetup.join, method: onUserJoinsMeetup }
            - { name: kernel.event_listener, event: kernel.terminate, method: generatePreferences }